# [Datasource]

spring:
  datasource:
    #JDBC驱动程序的完全限定名称。默认情况下，基于URL自动检测。
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接池实现的完全限定名称。默认情况下，它是从类路径中自动检测到的。
    type: com.zaxxer.hikari.HikariDataSource
    #
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
    #
    hikari:
      #自动提交
      auto-commit: true
      #连接超时时间
      connection-timeout: 30000
      #最大空闲时间
      idle-timeout: 600000
      #最大生命周期
      max-lifetime: 1800000
      #最小空闲连接数
      minimum-idle: 4
      #最大连接数
      maximum-pool-size: 10
      #连接池名
      pool-name: HikariPool-demo
      #连接有效的超时时间
      validation-timeout: 5000

#如果Mapper.xml与Mapper.class不在同一个包下或者不同名,就必须使用配置mapper-locations指定mapper.xml的位置.
mybatis-plus:
  #[mapper]路径
  mapper-locations: classpath:mapper/*.xml
  #[配置]
  configuration:
    #开启驼峰命名匹配
    map-underscore-to-camel-case: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    #输出sql语句
    com.buk.example.mapper: debug