
###
POST {{url}}/user
Content-Type: application/json

{
  "id": 1,
  "name": "post",
  "age": 1
}

###
GET {{url}}/user
Accept: application/json

###
GET {{url}}/user/1
Accept: application/json

###
PUT {{url}}/user/1
Content-Type: application/json

{
  "id": 1,
  "name": "put",
  "age": 1
}

###
DELETE {{url}}/user/1
Content-Type: application/json

###
