# [moreRedis]

spring:
  redis:

    #多数据源db1
    db1:
      #服务器地址
      host: 127.0.0.1
      #端口号
      port: 6379
      #数据库
      database: 1
      #密码
      password:
      #连接超时时间（毫秒）
      timeout: 6000
      #连接池
      lettuce:
        pool:
          #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          #连接池中的最小空闲连接
          min-idle: 4
          #连接池中的最大空闲连接
          max-idle: 8
          #连接池最大连接数（使用负值表示没有限制）
          max-active: 8

    #多数据源db2
    db2:
      #服务器地址
      host: 127.0.0.1
      #端口号
      port: 6379
      #数据库
      database: 2
      #密码
      password:
      #连接超时时间（毫秒）
      timeout: 6000
      #连接池
      lettuce:
        pool:
          #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          #连接池中的最小空闲连接
          min-idle: 4
          #连接池中的最大空闲连接
          max-idle: 8
          #连接池最大连接数（使用负值表示没有限制）
          max-active: 8